### ISSUE TITLE
Open TCP + UDP at the same time

### ISSUE THREAD

**Issue by cenapyuce** [YAL-Game-Tools/Steam-P2P-Adapter#2]
how can i open 2 ports at the same time for a game udp and tcp

**Comment by YellowAfterlife** [comment]
That is not something I had to consider. What game is that?

**Comment by cenapyuce** [comment]
> That is not something I had to consider. What game is that?

Half life 2 mod synergy

**Comment by YellowAfterlife** [comment]
Didn't know that, that's interesting

Steam allegedly supports up to 4 data transfer channels (which means that one can pretend to be UDP and another can pretend to be TCP), but this complicates the matters - right now the tool's logic is just "wait for a player to pop up in the lobby, talk to them until they leave or the socket closes", but with two sockets these need to be watched independently on two threads with some extra work to not upset Steam.

In the meantime I can suggest ZeroTier - haven't used my own tool in more than a year as that works pretty consistently.

**Comment by cenapyuce** [comment]
thx

**Comment by cenapyuce** [comment]
bro bro i’m stupid source is uses udp my bad
